name: Build and Release with ShadowJar

on:
  push:
    tags:
      - 'v*'   

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'       

    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew

    - name: Build shadowJar
      run: ./gradlew shadowJar

    - name: Upload release asset
      uses: softprops/action-gh-release@v2
      with:
        files: build/libs/*.jar    
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
